### ISSUE TITLE
Support Bitcoin

### ISSUE THREAD

**Issue by lf94** [FindETH/wallets#183]
Really it should support any cryptocurrency which the underlying wallets support.

**Comment by Mrtenz** [comment]
The cryptography used for each cryptocurrency is very different. This library is aimed for use in FindETH, which only supports Ethereum (as implied by the name), and Ethereum-like networks (e.g. Ethereum Classic, EnergyWebChain, etc.). I have no plans to add support for other cryptocurrencies like Bitcoin at the moment.
